config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.skg-if-openapi.elsst.server:
      branch: main
      repo: https://github.com/cessda/cessda.skg-if-openapi.elsst.server.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.skg-if-openapi.elsst.server git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-russet-peccary.sh
        container: qc.acc_hasty-cobalt-kingfisher
  QC.Doc:
    repos:
      github.com/cessda/cessda.skg-if-openapi.elsst.server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-magenta-akbash.sh
        container: qc.doc_cheeky-malachite-ocelot
      github.com/cessda/cessda.skg-if-openapi.elsst.server git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-ivory-akbash.sh
        container: qc.doc_foggy-platinum-salamander
      github.com/cessda/cessda.skg-if-openapi.elsst.server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-violet-tiger.sh
        container: qc.doc_sleepy-emerald-grouse
  QC.Lic:
    repos:
      github.com/cessda/cessda.skg-if-openapi.elsst.server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-saffron-zebra.sh
        container: qc.lic_scummy-lilac-yak
  QC.Met:
    repos:
      github.com/cessda/cessda.skg-if-openapi.elsst.server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-bistre-beaver.sh
        container: qc.met_greasy-amethyst-fox
  QC.Sec:
    repos:
      github.com/cessda/cessda.skg-if-openapi.elsst.server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-celadon-malamute.sh
        container: qc.sec_scummy-razzmatazz-bee
  QC.Sty:
    repos:
      github.com/cessda/cessda.skg-if-openapi.elsst.server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-ultramarine-ferret.sh
        container: qc.sty_shaky-chocolate-beagle
      github.com/cessda/cessda.skg-if-openapi.elsst.server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-malachite-clam.sh
        container: qc.sty_scanty-celadon-quokka
      github.com/cessda/cessda.skg-if-openapi.elsst.server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-fuchsia-olm.sh
        container: qc.sty_clammy-bronze-dog
  QC.Uni:
    repos:
      github.com/cessda/cessda.skg-if-openapi.elsst.server pytest:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-cream-butterfly.sh
        container: qc.uni_lousy-cinnabar-dachshund
  QC.Ver:
    repos:
      github.com/cessda/cessda.skg-if-openapi.elsst.server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-lavender-caiman.sh
        container: qc.ver_beady-magnolia-barnacle
timeout: 5400
